### ISSUE TITLE
Error: Couldn't find package "@cnoe-io/plugin-scaffolder-actions@0.1.1" required by "backend@0.0.0" on the "npm" registry.

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/backstage-app#11]
## Issue

```
yarn install
yarn install v1.22.19
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning @backstage/cli > eslint-plugin-deprecation@1.6.0: this package has been deprecated, please use v2.0.0
warning @backstage/cli > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @backstage/cli > react-dev-utils > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @backstage/cli > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @backstage/cli > rollup-plugin-dts > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning @backstage/cli > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning lerna > @lerna/bootstrap > read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
warning lerna > @lerna/bootstrap > read-package-tree > readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
warning lerna > @lerna/version > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/publish > npm-registry-fetch > @npmcli/ci-detect@1.4.0: this package has been deprecated, use `ci-info` instead
warning lerna > @lerna/bootstrap > read-package-tree > readdir-scoped-modules > debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/create > pacote > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning lerna > @lerna/create > pacote > @npmcli/run-script > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/plugin-workflows > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > app > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/integration-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-graph > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/app-defaults > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-import > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-api-docs > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-github-actions > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/core-components > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-org > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-search-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs-module-addons-contrib > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-scaffolder > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-scaffolder-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-search > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-kubernetes > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-tech-radar > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-user-settings > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > start-server-and-test@1.15.5: this package has been deprecated
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @roadiehq/backstage-plugin-argo-cd > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/test-utils > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @kubernetes/client-node > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @material-ui/lab@4.0.0-alpha.57: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/plugin-workflows > @material-ui/lab@4.0.0-alpha.57: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/integration-react > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-graph > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-import > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-api-docs > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-catalog-react > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-github-actions > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/core-components > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-org > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-search-react > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs-module-addons-contrib > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-scaffolder > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-scaffolder-react > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-search > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-kubernetes > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs-react > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-tech-radar > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-user-settings > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @roadiehq/backstage-plugin-argo-cd > @material-ui/lab@4.0.0-alpha.45: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @backstage/plugin-home > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @backstage/plugin-home > @material-ui/lab@4.0.0-alpha.61: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @backstage/dev-utils > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/core-components > @material-table/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs-react > @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @material-ui/core > @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-techdocs > @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/core-components > @material-table/core > @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > cypress > @cypress/request > qs@6.10.5: when using stringify with arrayFormat comma, `[]` is appended on single-item arrays. Upgrade to v6.11.0 or downgrade to v6.10.4 to fix.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > react-use > nano-css > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-auth-backend > passport-saml@3.2.4: For versions >= 4, please use scopped package @node-saml/passport-saml
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/backend-common > @aws-sdk/abort-controller@3.374.0: This package has moved to @smithy/abort-controller
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-kubernetes-backend > @aws-sdk/signature-v4@3.374.0: This package has moved to @smithy/signature-v4
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-scaffolder-backend > @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > @internal/cnoe-ui-plugin > @backstage/plugin-home > @backstage/plugin-home-react > @material-ui/core@4.12.4: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/core-components > @material-table/core > @material-ui/pickers@3.3.11: This package no longer supported. It has been relaced by @mui/x-date-pickers
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > app > @backstage/plugin-api-docs > @asyncapi/react-component > isomorphic-dompurify > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-techdocs-backend > @backstage/plugin-techdocs-node > @aws-sdk/node-http-handler@3.374.0: This package has moved to @smithy/node-http-handler
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-techdocs-backend > @backstage/plugin-techdocs-node > @trendyol-js/openstack-swift-sdk > axios-cached-dns-resolve > babel-polyfill > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning workspace-aggregator-0090e156-e35e-4533-8b8e-d0669e3d7e0c > backend > @backstage/plugin-techdocs-backend > @backstage/plugin-techdocs-node > @trendyol-js/openstack-swift-sdk > axios-cached-dns-resolve > babel-polyfill > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
error Couldn't find package "@cnoe-io/plugin-apache-spark@0.1.2" required by "app@0.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@cnoe-io/plugin-argo-workflows@0.1.3" required by "app@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@cnoe-io/plugin-argo-workflows@0.1.3" required by "app@link:packages/app" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@cnoe-io/plugin-scaffolder-actions-frontend@0.1.1" required by "app@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@cnoe-io/plugin-scaffolder-actions-frontend@0.1.1" required by "app@link:packages/app" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@cnoe-io/plugin-apache-spark@0.1.2" required by "app@link:packages/app" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@cnoe-io/plugin-scaffolder-actions@0.1.1" required by "backend@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by cmoulliard** [comment]
I cannot reproduce anymore this error
